// Generated by CoffeeScript 1.4.0
(function() {
  var Album;

  Album = (function() {

    function Album(uri) {
      this.uri = uri;
      this.imgUri = 'images/album.png';
    }

    Album.prototype.loadImgUri = function(webService) {
      var _this = this;
      this.webService = webService;
      return this.webService.query('albumImg', {
        uri: this.uri
      }).then(function(httpRes) {
        return _this.imgUri = httpRes.data.uri;
      });
    };

    return Album;

  })();

}).call(this);
