// Generated by CoffeeScript 1.4.0
(function() {
  var HomeController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  HomeController = (function() {

    function HomeController($scope, trackQueue, spotify) {
      this.trackQueue = trackQueue;
      this.spotify = spotify;
      this.buildCurrenTrack = __bind(this.buildCurrenTrack, this);

      this.onTrackClick = __bind(this.onTrackClick, this);

      this.scope = $scope;
      this.scope.trackQueue = this.trackQueue;
      this.scope.spotify = this.spotify;
    }

    HomeController.prototype.onSearchBtnClick = function() {
      return this.searchPanel.show();
    };

    HomeController.prototype.onTrackClick = function(e) {
      var uri;
      uri = e.uri;
      if (this.app.getUser().haveVote(uri)) {
        return this.app.getUser().unvote(uri);
      } else {
        return this.app.getUser().vote(uri);
      }
    };

    HomeController.prototype.buildQueue = function() {
      var data, elem, func, res, _i, _len, _ref,
        _this = this;
      res = [];
      _ref = this.app.getQueue();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        elem = _ref[_i];
        data = {};
        data.uri = elem.uri;
        data.trackName = (elem.track != null) ? elem.track.name : '...';
        data.artistName = (elem.track != null) ? elem.track.artists[0].name : '...';
        data.albumImg = (elem.track != null) ? Model.getAlbumImg(elem.track.album.uri) : Model.getAlbumImg(null);
        data.nbVotes = elem.nbVotes;
        func = function() {
          var uri;
          uri = data.uri;
          return function() {
            return _this.app.getUser().haveVote(uri);
          };
        };
        func = func();
        data.haveMyVote = ko.computed(func);
        res.push(data);
      }
      return res;
    };

    HomeController.prototype.buildCurrenTrack = function() {
      var data, elem;
      elem = this.app.getCurrentTrack();
      if (!(elem != null)) {
        return {
          uri: '',
          trackName: '',
          artistName: '',
          albumImg: '',
          nbVotes: 0
        };
      }
      data = {};
      data.uri = elem.uri;
      data.trackName = (elem.track != null) ? elem.track.name : '...';
      data.artistName = (elem.track != null) ? elem.track.artists[0].name : '...';
      data.albumImg = (elem.track != null) ? Model.getAlbumImg(elem.track.album.uri) : Model.getAlbumImg(null);
      data.nbVotes = elem.nbVotes;
      return data;
    };

    return HomeController;

  })();

}).call(this);
