// Generated by CoffeeScript 1.4.0
(function() {
  var spotifyDj;

  spotifyDj = angular.module('spotifyDj', []);

  spotifyDj.config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/home', {
        templateUrl: "./pages/home.html",
        controller: HomeController
      });
      return $routeProvider.otherwise({
        redirectTo: '/home'
      });
    }
  ]);

  spotifyDj.factory('webService', function($http) {
    return new WebService($http);
  });

  spotifyDj.factory('trackQueue', function(webService, spotify) {
    return new TrackQueue(webService);
  });

  spotifyDj.factory('user', function(webService, trackQueue) {
    return new User(webService, trackQueue);
  });

  spotifyDj.factory('spotify', function($cacheFactory, webService) {
    return new Spotify($cacheFactory, webService);
  });

}).call(this);
