// Generated by CoffeeScript 1.4.0
(function() {
  var Spotify;

  Spotify = (function() {

    function Spotify($cacheFactory, webService) {
      this.webService = webService;
      this.cache = $cacheFactory('Spotify');
    }

    Spotify.prototype.getAlbum = function(uri) {
      var album, res;
      res = this.cache.get(uri);
      if (res != null) {
        return res;
      }
      album = new Album(uri);
      album.loadImgUri(this.webService);
      this.cache.put(uri, album);
      return album;
    };

    return Spotify;

  })();

}).call(this);
